# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 973d0c5a99e29fb8a6d28c9a3773245d4e3a37aba9dc230aed5165eb2a5696af2d57e5bee855b3d4b4e5e30b4f514280833a323edd522ded5a05f82310db53cb

test:
  secret_key_base: 15e09a098487d8ea6079c604ea671ae3240d56fddfabace68fedb0bb968fa76ede0cadc88fef3ee998f27df53b56c310e679a6d9a6f0b2e399546aa383301ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
